### ISSUE TITLE
Question: Deploying to Azure via FTP

### ISSUE THREAD

**Issue by simax** [isaacabraham/fsharp-demonstrator#1]
I'm trying to deploy a  `Suave` web app to `Azure`, initially via `HTTP` but not having much luck. The official `Suave.io` site says just `FTP` your application and it should just work. 

But exactly which files do I deploy?

I've created a web app on Azure and I have the correct `FTP` creds and using `FileZilla` I can see the `wwwroot` folder. 

If I wanted to deploy the ```Suave``` app from this repo, which files would I upload? 

Once I've got things working via `FTP` I want to continue to experiment and deploy from `github`.

I realise this is not an issue with your repo. I just wondered if you could advise.

**Comment by isaacabraham** [comment]
Hi. Copy the whole application to wwwroot, along with a web.config file that is required to redirect IIS traffic through to your Suave app. See my post here for more details: 

https://cockneycoder.wordpress.com/2016/04/08/hosting-suave-in-the-azure-app-service/

If the docs on the Suave site aren't detailed enough, please do submit a PR to make them even better :)

**Comment by simax** [comment]
Thanks, I've already read the blog post you mentioned, thats why I'm posting this question here. Thanks for writing that by the way, once I've managed to FTP stuff up I will dig into your article more and try and deploy directly from git.

When you say copy the whole application, I FTP'd the files from `fsharp-demonstrator/src/SuaveHost` because thats the folder that contains the `web.config` file.  

But when I try and access my app at http://me-time.azurewebsites.net/ I get the error:
`The specified CGI application encountered an error and the server terminated the process.`

Any idea why?

**Comment by isaacabraham** [comment]
Hmmm. Make sure the web.config path points to the Suave host executable. That should work.

I do vaguely remember getting this error. It's usually a problem with the web config not set up correctly or the Suave app crashing on start-up.

Is this the same source code as my repo or anything else?

**Comment by simax** [comment]
Hi Isaac, the steps I took were as follows.

1. Created a new web app in Azure called `Me-Time` using a `resource group` and `app service plan` of the same name. All on the `Free Tier`. 
2. Downloaded the `me-time.publishsettings` file that Azure created.
3. Cloned this repo
4. Used `FileZilla` to connect via `FTP` using the creds from `step 2`
5. Uploaded the files (via `FTP`) from `fsharp-demonstrator/src/SuaveHost` from the repo cloned at `step 3` to the `site\wwwroot` on Azure.
6. Navigated to me-time.azurewebsites.net/

Then I receive the error `The specified CGI application encountered an error and the server terminated the process.`

(When I look at the folders on `Azure` under `site\wwwroot` I don't see an `obj` or `bin` folders. I don't think any `msbuild` process occurred. That doesn't seem right.)

Is there any chance you could repeat the steps I've taken to see if you get the same results?

**Comment by isaacabraham** [comment]
Aha. Now I get it (and apologies for the long delay in the answer). So - you either need to FTP up the *binaries* (so build locally and FTP them up) *OR* use source control hooks in the Azure App Service and set up a Kudu build. Out of the box I think the default App Service Kudu / source control integration should find a solution, build it and copy across to wwwroot - so it should "just work".

But the main issue you have is - you're deploying source code into wwwroot; either build locally and deploy the binaries via FTP, or use App Service's source control feature to download source code onto the app service and build there before deploying to wwwroot.

**Comment by simax** [comment]
Hi Isaac, 

Thanks for replying. Yes I realised that too after a while. Make sense that I would need to build the binaries locally before FTP'ing. 

Haven't had a chance to try it out yet. In fact I think my Azure 30 day evaluation has now expired so I may have to upgrade my subscription because I also want to try the source control method. 

P.S. Also really enjoyed your skillscast video "Turbo Charge your F# with Azure".

**Comment by isaacabraham** [comment]
I *think* that you can still try source code deployment with app service. You just can't use anything but the free tier if you don't want to start paying.

**Comment by simax** [comment]
Yeh, managed to deploy via a local git repo!
